# Relurpify Agent Manifest Template
# This file defines the security contract, runtime environment, and default agent configuration.
# It serves as the source of truth for the PermissionManager and Sandbox.

apiVersion: relurpify/v1alpha1
kind: AgentManifest

metadata:
  name: "template-agent"
  version: "1.0.0"
  description: "A template configuration showing all available options."

spec:
  # Container Runtime Configuration
  # -----------------------------------------------------------------------------
  image: "ghcr.io/lexcodex/relurpify/runtime:latest"
  runtime: "gvisor" # Currently only "gvisor" is supported for strict isolation

  # Permission Configuration (Enforced by PermissionManager)
  # -----------------------------------------------------------------------------
  permissions:
    # Filesystem Access
    filesystem:
      - action: "fs:read"
        path: "${workspace}/**"
        justification: "Read access to the entire workspace"
      - action: "fs:write"
        path: "${workspace}/src/**"
        justification: "Allow writing source code"
        hitl_required: false # Set to true to require Human-In-The-Loop approval for every write
      - action: "fs:execute"
        path: "${workspace}/scripts/**"
        justification: "Allow executing scripts in the scripts directory"
      - action: "fs:list"
        path: "${workspace}/**"
    
    # Executable Allowlist (for CommandTool / ExecuteCodeTool)
    executables:
      - binary: "go"
        args: ["test", "./..."]
        env: ["CGO_ENABLED=1"]
        hitl_required: false
      - binary: "npm"
        args: ["install", "*"]
        hitl_required: true # Require approval for installing packages
      - binary: "bash"
        args: ["-c", "*"]
      - binary: "touch"
      - binary: "echo"
    
    # Network Access
    network:
      - direction: "egress"
        protocol: "tcp"
        host: "api.github.com"
        port: 443
        description: "GitHub API access"
      - direction: "egress"
        protocol: "tcp"
        host: "proxy.golang.org"
        port: 443
        description: "Go module proxy"
      - direction: "ingress" # Typically blocked, but can be defined
        protocol: "tcp"
        port: 8080
    
    # Linux Capabilities (Advanced Sandbox Configuration)
    capabilities:
      - capability: "CAP_NET_BIND_SERVICE"
        justification: "Allow binding to privileged ports"

    # IPC (Inter-Process Communication)
    ipc:
      - kind: "signal"
        target: "pid:1"
        description: "Allow sending signals to init process"

    # Global HITL Requirements
    # List of high-risk categories that always require approval regardless of specific rules
    hitl_required: 
      - "net:egress"
      - "exec:*"

  # Resource Quotas (Enforced by Sandbox/Container Runtime)
  # -----------------------------------------------------------------------------
  resources:
    limits:
      cpu: "2"           # 2 vCPUs
      memory: "4Gi"      # 4 Gigabytes RAM
      disk_io: "100MBps" # Disk I/O throughput limit
      network: "1Gbps"   # Network bandwidth limit

  # Security Context
  # -----------------------------------------------------------------------------
  security:
    run_as_user: 1000        # UID to run the agent process as
    read_only_root: true     # Mount root filesystem as read-only
    no_new_privileges: true  # Prevent gaining new privileges (setuid/setgid)

  # Audit Logging
  # -----------------------------------------------------------------------------
  audit:
    level: "verbose"    # "basic", "verbose", "debug"
    retention_days: 30  # How long to keep audit logs locally

  # Agent Runtime Configuration
  # -----------------------------------------------------------------------------
  # This section configures the default agent logic and capabilities.
  # Additional agents can be defined in relurpify_cfg/agents/*.yaml
  agent:
    # Agent Implementation
    # Options: "coding", "planner", "react", "reflection", "expert"
    implementation: "expert"
    
    mode: "primary" # "primary", "subagent", "system"
    version: "v1"
    prompt: "You are a helpful coding assistant..." # System prompt override

    # Language Model Configuration
    model:
      provider: "ollama"
      name: "codellama:7b"
      temperature: 0.2
      max_tokens: 4096

    # Tool Capabilities (Toggle builtin tool categories)
    tools:
      file_read: true
      file_write: true
      file_edit: true
      bash_execute: true
      lsp_query: true
      search_codebase: true
      web_search: false

    # Per-tool Policies (Visibility + Execution)
    # These are evaluated in addition to the coarse tool matrix above.
    tool_policies:
      exec_run_code:
        visible: true
        execute: "ask" # "allow", "deny", "ask"
      exec_run_linter:
        execute: "allow"

    # Bash Execution Constraints
    bash_permissions:
      default: "ask" # "allow", "deny", "ask"
      allow_patterns:
        - "ls -la"
        - "grep *"
      deny_patterns:
        - "rm -rf /"
        - "wget *"

    # File Permission Constraints (Agent-level scopes)
    file_permissions:
      write:
        default: "ask"
        allow_patterns: ["src/**", "tests/**"]
        deny_patterns: ["config/secrets.yaml"]
        require_approval: true
      edit:
        default: "allow"
        allow_patterns: ["**/*.go", "**/*.md"]
        documentation_only: false

    # Sub-agent Invocation Settings
    invocation:
      can_invoke_subagents: true
      allowed_subagents: ["reviewer", "architect"]
      max_depth: 3

    # Context Management
    context:
      max_files: 50
      max_tokens: 16000
      include_git_history: true
      include_dependencies: false
      compression_strategy: "hybrid" # "summary", "truncate", "hybrid"
      progressive_loading: true      # Load file details on-demand based on relevance

    # Language Server Protocol (LSP) Features
    lsp:
      enabled: true
      timeout: "30s"
      servers:
        go: "gopls"
        python: "pyright"
        typescript: "typescript-language-server"

    # Search & Indexing Capabilities
    search:
      hybrid_enabled: true # Use both vector and AST analysis
      vector_index: true   # Maintain semantic vector index
      ast_index: true      # Parse and index code structure (symbols, refs)

    # Display Metadata
    metadata:
      author: "Relurpify Team"
      priority: 10
      tags: ["general", "coding"]

    # Toggle Ollama Native Tool Calling features
    ollama_tool_calling: true

    # Debug Logging
    logging:
      llm: true   # Log full LLM prompts/responses
      agent: true # Log agent internal state transitions
